version: "2"
services:
  # https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ddd.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    ports: # uses 5672 internally
      - 15673:15672

  frontdesk-db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: ddd.frontdesk-db
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - 1434:1433 # exposed just for debugging purposes

  frontdesk-api:
    build:
      context: .
      dockerfile: ./FrontDesk/src/FrontDesk.Api/Dockerfile
    image: ddd.frontdesk.api
    container_name: ddd.frontdesk.api
    ports:
      - 5200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://192.168.1.158+"
    restart: always
    depends_on:
      - rabbitmq
      - frontdesk-db

  frontdesk-blazor:
    build:
      context: .
      dockerfile: ./FrontDesk/src/FrontDesk.Blazor.Host/Dockerfile
    image: ddd.frontdesk.blazor
    container_name: ddd.frontdesk.blazor
    ports:
      - 5100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://192.168.1.158+"
    restart: always
    depends_on:
      - frontdesk-api

  clinicmanagement-db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: ddd.clinicmanagement-db
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - 1435:1433 # exposed just for debugging purposes

  clinicmanagement-api:
    build:
      context: .
      dockerfile: ./ClinicManagement/src/ClinicManagement.Api/Dockerfile
    image: ddd.clinicmanagement.api
    container_name: ddd.clinicmanagement.api
    ports:
      - 6200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://192.168.1.158+"
    restart: always
    depends_on:
      - rabbitmq
      - clinicmanagement-db

  clinicmanagement-blazor:
    build:
      context: .
      dockerfile: ./ClinicManagement/src/ClinicManagement.Blazor.Host/Dockerfile
    image: ddd.clinicmanagement.blazor
    container_name: ddd.clinicmanagement.blazor
    ports:
      - 6100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://192.168.1.158+"
    restart: always
    depends_on:
      - clinicmanagement-api

  mailserver:
    image: jijiechen/papercut:latest
    container_name: ddd.papercut
    ports: # exposes port 25 internally
      - 37409:37408

  vet-clinic-public:
    build:
      context: .
      dockerfile: ./VetClinicPublic/src/VetClinicPublic/Dockerfile
    image: ddd.vet-clinic-public
    container_name: ddd.vet-clinic.public
    ports:
      - 7100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://192.168.1.158+"
    restart: always
    depends_on:
      - rabbitmq
      - mailserver
